Repository Be09-Fin-Pado/InFlow-FE, pull requests merged in 2024-12, with the labels that each got.

#80 Feat: 사원 검색 컴포넌트 구현, 휴가 정책 페이지 구현
  inflow/src/api/department.js
  inflow/src/components/common/SearchEmployeeComponent.vue
  inflow/src/views/hr-basic/attendance/LeaveRequestsView.vue
  inflow/src/views/hr-basic/attendance/LeaveView.vue
  inflow/src/views/hr-basic/attendance/OvertimeRequestsView.vue
  inflow/src/views/hr-basic/attendance/ReturnRequestsView.vue
  inflow/src/views/hr-basic/attendance/ReturnView.vue
  inflow/src/views/hr-basic/attendance/VacationRequestsView.vue
  inflow/src/views/hr-basic/attendance/VacationView.vue
  inflow/src/views/hr-management/vacation/VacationPaymentView.vue
  inflow/src/views/hr-management/vacation/VacationPolicyView.vue
Labels: enhancement

#83 Feat: 부서 폴더 UI 을 통해 사원 목록 조회 , 사원 상세정보 조회
  inflow/src/assets/icons/fold.png
  inflow/src/assets/icons/unfold.png
  inflow/src/components/employee-search/DepartmentHeirarchy.vue
  inflow/src/components/employee-search/EmployeeDetail.vue
  inflow/src/components/employee-search/EmployeeList.vue
  inflow/src/components/employee-search/SearchBar.vue
  inflow/src/components/employee-search/TreeNode.vue
  inflow/src/views/emp-search/EmployeeSearchView.vue
Labels: enhancement

#84 Feat: 근태, 휴가 신청 취소 기능 구현
  inflow/src/api/attendance.js
  inflow/src/api/vacation.js
  inflow/src/components/attendance/CancelRequestModal.vue
  inflow/src/components/modals/ModalItem.vue
  inflow/src/views/hr-basic/attendance/BusinessTripRequestsView.vue
  inflow/src/views/hr-basic/attendance/BusinessTripView.vue
  inflow/src/views/hr-basic/attendance/DispatchRequestsView.vue
  inflow/src/views/hr-basic/attendance/DispatchView.vue
  inflow/src/views/hr-basic/attendance/LeaveRequestsView.vue
  inflow/src/views/hr-basic/attendance/LeaveView.vue
  inflow/src/views/hr-basic/attendance/OvertimeRequestsView.vue
  inflow/src/views/hr-basic/attendance/OvertimeView.vue
  inflow/src/views/hr-basic/attendance/RemoteRequestsView.vue
  inflow/src/views/hr-basic/attendance/RemoteView.vue
  inflow/src/views/hr-basic/attendance/ReturnRequestsView.vue
  inflow/src/views/hr-basic/attendance/ReturnView.vue
  inflow/src/views/hr-basic/attendance/VacationRequestsView.vue
  inflow/src/views/hr-basic/attendance/VacationView.vue
Labels: enhancement

#85 표준근로계약서 서명
  inflow/src/api/emp_info.js
  inflow/src/views/hr-basic/ContractView.vue
  inflow/src/views/hr-basic/document/CertificateView.vue
  inflow/src/views/hr-basic/document/ContractSignView.vue
  inflow/src/views/hr-basic/document/EmployeeContractModal.vue
  inflow/src/views/hr-basic/document/SecurityContractModal.vue
Labels: enhancement

#86 Refactor: 빈 배열 조건문 변경
  inflow/src/views/hr-basic/attendance/BusinessTripRequestsView.vue
  inflow/src/views/hr-basic/attendance/BusinessTripView.vue
  inflow/src/views/hr-basic/attendance/CommuteView.vue
  inflow/src/views/hr-basic/attendance/DispatchRequestsView.vue
  inflow/src/views/hr-basic/attendance/DispatchView.vue
  inflow/src/views/hr-basic/attendance/LeaveRequestsView.vue
  inflow/src/views/hr-basic/attendance/LeaveView.vue
  inflow/src/views/hr-basic/attendance/OvertimeRequestsView.vue
  inflow/src/views/hr-basic/attendance/OvertimeView.vue
  inflow/src/views/hr-basic/attendance/RemoteRequestsView.vue
  inflow/src/views/hr-basic/attendance/RemoteView.vue
  inflow/src/views/hr-basic/attendance/ReturnRequestsView.vue
  inflow/src/views/hr-basic/attendance/ReturnView.vue
  inflow/src/views/hr-basic/attendance/VacationRequestsView.vue
  inflow/src/views/hr-basic/attendance/VacationView.vue
  inflow/src/views/hr-management/vacation/VacationPaymentView.vue
  inflow/src/views/hr-management/vacation/VacationPolicyView.vue
Labels: enhancement

#87 Refactor: 페이지 로드 시 전체 사원 목록이 조회되도록 수정
  inflow/src/views/emp-search/EmployeeSearchView.vue
Labels: enhancement

#89 Feat: 인사기본 사원 경력 정보 조회 및 수정 구현
  inflow/package-lock.json
  inflow/package.json
  inflow/src/api/emp_attach.js
  inflow/src/components/common/SelectAppTypeComponent.vue
  inflow/src/components/dropdowns/AppointmentHisDropDown.vue
  inflow/src/router/index.js
  inflow/src/views/hr-basic/MyInfoView.vue
  inflow/src/views/hr-basic/document/EmployeeContractModal.vue
  inflow/src/views/hr-basic/employee/CareerInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
  inflow/src/views/hr-management/AppointmentManagementView.vue
  inflow/src/views/hr-management/EmployeeUploadView.vue
  inflow/src/views/hr-management/appointment/AppointmentHistoryView.vue
  inflow/src/views/hr-management/appointment/AppointmentUploadView.vue
  inflow/src/views/hr-management/employee-upload/CareerInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/DisciplineRewardInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EducationInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/FamilyMemberInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/LanguageTestInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/QualificationInfoUploadView.vue
Labels: enhancement

#88 비밀 유지 서약서 기능 추가
  inflow/src/main.js
  inflow/src/views/hr-basic/document/ContractSignView.vue
  inflow/src/views/hr-basic/document/EmployeeContractModal.vue
  inflow/src/views/hr-basic/document/SecurityContractModal.vue
Labels: enhancement

#92 Feat: 인사기본 학력정보 조회 및 수정 구현
  inflow/src/api/emp_attach.js
  inflow/src/router/index.js
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoView.vue
Labels: enhancement

#91 재직 증명서 발급 기능 추가
  inflow/src/views/hr-basic/document/CertificateModal.vue
  inflow/src/views/hr-basic/document/CertificateView.vue
Labels: enhancement

#94 Feat: 나의 근태 현황 위젯 구현
  inflow/src/components/widgets/MyAttendanceWidget.vue
  inflow/src/components/widgets/WidgetItem.vue
  inflow/src/views/home/HomeView.vue
  inflow/src/views/hr-basic/attendance/OvertimeView.vue
Labels: enhancement

#96 Feat: 퇴직금 예상치 조회 화면 구현
  inflow/src/api/payroll.js
  inflow/src/router/index.js
  inflow/src/views/hr-basic/SalaryView.vue
  inflow/src/views/hr-basic/salary/SalaryListView.vue
  inflow/src/views/hr-basic/salary/SeverancePayView.vue
Labels: enhancement

#98 Feat: 사원 개인의 가족 정보 조회 및 수정 구현 & 사원 개인의 포상 및 징계 조회 구현
  inflow/src/api/emp_attach.js
  inflow/src/components/dropdowns/DisciplineRewardTypeDropDown.vue
  inflow/src/router/index.js
  inflow/src/views/hr-basic/MyInfoView.vue
  inflow/src/views/hr-basic/employee/DisciplineRewardInfoView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoView.vue
Labels: enhancement

#99 프로필 수정 시 로딩 추가
  inflow/src/views/hr-basic/document/CertificateModal.vue
  inflow/src/views/hr-basic/document/EmployeeContractModal.vue
  inflow/src/views/hr-basic/document/SecurityContractModal.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
Labels: enhancement

#100 Feat: 홈화면 초기 세팅
  inflow/package-lock.json
  inflow/src/components/common/CommonHeader.vue
  inflow/src/components/dropdowns/ThirtyMinuteDropDown.vue
  inflow/src/components/dropdowns/TimeDropDown.vue
  inflow/src/components/semantic/GridItem.vue
  inflow/src/components/widgets/MyAttendanceWidget.vue
  inflow/src/components/widgets/MyScheduleWidget.vue
  inflow/src/components/widgets/MyTeamMemberWidget.vue
  inflow/src/components/widgets/ScheduleDdayWidget.vue
  inflow/src/views/home/HomeView.vue
  inflow/src/views/hr-basic/attendance/OvertimeView.vue
  inflow/src/views/hr-management/vacation/VacationPaymentView.vue
Labels: enhancement

#104 로딩 컴포넌트 추가
  inflow/src/components/common/LoadingOverlay.vue
  inflow/src/views/hr-basic/document/CertificateModal.vue
  inflow/src/views/hr-basic/document/EmployeeContractModal.vue
  inflow/src/views/hr-basic/document/SecurityContractModal.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
Labels: enhancement

#109 Feat: 비정기 수당 관리 화면
  inflow/src/api/payroll.js
  inflow/src/router/index.js
  inflow/src/views/hr-management/Salary/IrregularAllowanceView.vue
  inflow/src/views/hr-management/SalaryManagementView.vue
Labels: enhancement

#110 Fix: 엑셀 양식 다운로드 에러 버그 수정
  inflow/src/views/hr-management/appointment/AppointmentUploadView.vue
  inflow/src/views/hr-management/employee-upload/CareerInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/DisciplineRewardInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EducationInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/FamilyMemberInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/LanguageTestInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/QualificationInfoUploadView.vue
Labels: bug

#111 Refactor: 피드백 반영
  inflow/src/components/employee-search/DepartmentHeirarchy.vue
  inflow/src/components/employee-search/TreeNode.vue
  inflow/src/components/widgets/MyTeamMemberWidget.vue
  inflow/src/views/home/HomeView.vue
  inflow/src/views/hr-basic/attendance/BusinessTripRequestsView.vue
  inflow/src/views/hr-basic/attendance/BusinessTripView.vue
  inflow/src/views/hr-basic/attendance/DispatchRequestsView.vue
  inflow/src/views/hr-basic/attendance/DispatchView.vue
  inflow/src/views/hr-basic/attendance/LeaveRequestsView.vue
  inflow/src/views/hr-basic/attendance/LeaveView.vue
  inflow/src/views/hr-basic/attendance/OvertimeRequestsView.vue
  inflow/src/views/hr-basic/attendance/OvertimeView.vue
  inflow/src/views/hr-basic/attendance/RemoteRequestsView.vue
  inflow/src/views/hr-basic/attendance/RemoteView.vue
  inflow/src/views/hr-basic/attendance/ReturnRequestsView.vue
  inflow/src/views/hr-basic/attendance/ReturnView.vue
  inflow/src/views/hr-basic/attendance/VacationRequestsView.vue
  inflow/src/views/hr-basic/attendance/VacationView.vue
  inflow/src/views/hr-basic/document/EmployeeContractModal.vue
  inflow/src/views/hr-basic/document/SecurityContractModal.vue
  inflow/src/views/hr-basic/my-department/SearchDepartmentMember.vue
Labels: enhancement

#112 Feat : 평가 관련 컴포넌트 개발
  inflow/src/api/evaluation.js
  inflow/src/api/evalution.js
  inflow/src/router/index.js
  inflow/src/views/evaluation/DeptTaskManageView.vue
  inflow/src/views/evaluation/EvalGradeUpdateModalView.vue
  inflow/src/views/evaluation/EvalGradeView.vue
  inflow/src/views/evaluation/EvalPolicyManagementView.vue
  inflow/src/views/evaluation/EvalPolicyView.vue
  inflow/src/views/evaluation/EvalTaskView.vue
  inflow/src/views/evaluation/EvalTypeManagementView.vue
  inflow/src/views/evaluation/FeedbackManageView.vue
  inflow/src/views/evaluation/LeaderEvalListView.vue
  inflow/src/views/evaluation/LeaderEvalView.vue
  inflow/src/views/evaluation/PersonalEvalCreateAndFindView.vue
  inflow/src/views/evaluation/PersonalEvalFindView.vue
  inflow/src/views/evaluation/PersonalEvalView.vue
  inflow/src/views/evaluation/TaskEvalModal.vue
  inflow/src/views/evaluation/TaskPolicyView.vue
Labels: enhancement

#123 Refactor: 메뉴 구성 수정
  inflow/src/views/hr-management/AppointmentManagementView.vue
  inflow/src/views/hr-management/ContractManagementView.vue
  inflow/src/views/hr-management/DepartmentManagementView .vue
  inflow/src/views/hr-management/EmployeeInfoView.vue
  inflow/src/views/hr-management/EmployeeUploadView.vue
  inflow/src/views/hr-management/EvalManagementView.vue
  inflow/src/views/hr-management/SalaryManagementView.vue
  inflow/src/views/hr-management/VacationManagementView.vue
Labels: enhancement

#124 Fix: router 오류 해결
  inflow/src/router/index.js
  inflow/src/views/evaluation/leader/FeedbackManageView.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
Labels: bug, enhancement

#125 Client : 평가 등급 CSS 스타일 수정 및 함수 추가
  inflow/src/api/evaluation.js
  inflow/src/views/evaluation/EvalGradeView.vue
Labels: enhancement

#126 Refactor: 재직증명서에 재직기간 추가
  inflow/src/views/hr-basic/document/CertificateModal.vue
Labels: enhancement

#127 Refactor: 타이머 시간 연장
  inflow/src/components/common/CommonHeader.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
  inflow/src/views/login/LoginView.vue
Labels: enhancement

#128 Refactor: 과제 등록과 할당 메뉴 분리
  inflow/src/router/index.js
  inflow/src/views/evaluation/LeaderEvalView.vue
  inflow/src/views/evaluation/leader/DeptTaskAssignView.vue
  inflow/src/views/evaluation/leader/DeptTaskUploadView.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
Labels: enhancement

#131 Fix: 라우터 수정
  inflow/src/router/index.js
  inflow/src/views/evaluation/LeaderEvalView.vue
  inflow/src/views/evaluation/leader/DeptTaskUploadView.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
Labels: bug, enhancement

#132 Feat: 리더 평가 초기 세팅
  inflow/src/views/evaluation/LeaderEvalView.vue
  inflow/src/views/evaluation/leader/DeptTaskAssignView.vue
  inflow/src/views/evaluation/leader/DeptTaskUploadView.vue
  inflow/src/views/evaluation/leader/FeedbackManageView.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
Labels: enhancement

#134 Client : 평가 유형 삭제 기능, 평가 정책 상세 페이지 추가
  inflow/src/api/evaluation.js
  inflow/src/views/evaluation/EvalPolicyManagementView.vue
  inflow/src/views/evaluation/EvalPolicyUpdateAndViewModal.vue
  inflow/src/views/evaluation/EvalTypeManagementView.vue
Labels: enhancement

#135 Refactor: 타이머 시계 아이콘으로 변경
  inflow/src/components/common/CommonHeader.vue
  inflow/src/components/icons/ClockIcon.vue
Labels: enhancement

#136 Refactor: 리더 평가 UI 변경
  inflow/src/router/index.js
  inflow/src/views/evaluation/PersonalEvalView.vue
  inflow/src/views/evaluation/leader/DeptTaskAssignView.vue
  inflow/src/views/evaluation/leader/DeptTaskUploadView.vue
  inflow/src/views/evaluation/leader/FeedbackManageView.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
Labels: enhancement

#137 Refactor: 평가 router 수정
  inflow/src/components/common/CommonNav.vue
  inflow/src/router/index.js
  inflow/src/views/evaluation/EvalPolicyView.vue
  inflow/src/views/evaluation/EvalTaskView.vue
  inflow/src/views/statistics/StatisticsView.vue
Labels: enhancement

#138 Feat: 미완성 설정 모달 컴포넌트 구현
  inflow/src/assets/admin_default_profile.png
  inflow/src/components/buttons/SettingButton.vue
  inflow/src/components/common/CommonHeader.vue
  inflow/src/components/modals/SettingModal.vue
  inflow/src/router/index.js
Labels: enhancement

#140 Client : 리더평가 조회 페이지 API 연동
  inflow/src/views/evaluation/EvalTaskView.vue
  inflow/src/views/evaluation/PersonalEvalCreateAndFindView.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
Labels: enhancement

#141 Feat: 홈 화면 구현
  inflow/src/api/emp_info.js
  inflow/src/components/buttons/CaretLeftButton.vue
  inflow/src/components/buttons/CaretRightButton.vue
  inflow/src/components/icons/CaretLeftIcon.vue
  inflow/src/components/icons/CaretRightIcon.vue
  inflow/src/components/nav/MonthSelectNav.vue
  inflow/src/components/widgets/MyScheduleWidget.vue
  inflow/src/components/widgets/ScheduleDdayWidget.vue
  inflow/src/views/home/HomeView.vue
Labels: enhancement

#142 Fix : 피드백 및 사원별 과제 API 호출 에러 해결
  inflow/src/api/evaluation.js
  inflow/src/views/evaluation/EvalPolicyManagementView.vue
  inflow/src/views/evaluation/leader/DeptTaskUploadView.vue
  inflow/src/views/evaluation/leader/FeedbackManageView.vue
Labels: enhancement

#144 Feat: 부서 관리 - 부서 목록 검색 및 조회, 부서 정보 상세조회 및 수정
  inflow/src/components/employee-search/TreeNode.vue
  inflow/src/router/index.js
  inflow/src/views/hr-management/DepartmentManagementView .vue
  inflow/src/views/hr-management/department/DepartmentManagementAddView.vue
  inflow/src/views/hr-management/department/DepartmentManagementInformationView.vue
  inflow/src/views/hr-management/department/DepartmentSearch.vue
Labels: enhancement

#146 Feat: 부서 추가 기능
  inflow/src/router/index.js
  inflow/src/views/hr-management/department/DepartmentManagementAddView.vue
Labels: enhancement

#147 Refactor: 사원 등록 css 수정
  inflow/src/views/hr-management/EmployeeUploadView.vue
  inflow/src/views/hr-management/employee-upload/CareerInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/DisciplineRewardInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EducationInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/FamilyMemberInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/LanguageTestInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/QualificationInfoUploadView.vue
Labels: enhancement

#148 Refactor: 인사 발령 css 수정
  inflow/src/views/hr-management/appointment/AppointmentUploadView.vue
Labels: enhancement

#149 Refactor: 개인신상관리 하단 css 수정
  inflow/src/components/common/CommonArticle.vue
  inflow/src/views/hr-basic/employee/CareerInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/DisciplineRewardInfoView.vue
  inflow/src/views/hr-basic/employee/EducationInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoView.vue
  inflow/src/views/hr-management/appointment/AppointmentHistoryView.vue
Labels: enhancement

#150 Feat : 부서별 인원에게 과제 할당 기능 추가
  inflow/src/api/evaluation.js
  inflow/src/views/evaluation/leader/DeptTaskAssignView.vue
  inflow/src/views/evaluation/leader/FeedbackManageView.vue
  inflow/src/views/evaluation/leader/TaskEvalCreateAndUpdateModal.vue
Labels: enhancement

#151 Refactor: 개인신상관리 상단 css 수정
  inflow/src/components/dropdowns/DisciplineRewardTypeDropDown.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
Labels: enhancement

#152 Refactor : 개인 과제 조회 페이지 CSS 스타일 수정
  inflow/src/views/evaluation/PersonalEvalFindView.vue
Labels: enhancement

#156 Refactor: 인사관리 - 사원별 급여내역 리팩토링 (연도별 조회로 수정)
  inflow/src/api/payroll.js
  inflow/src/components/common/ChangeYearComponent.vue
  inflow/src/views/hr-management/Salary/EmployeeSalaryListView.vue
Labels: enhancement

#157 Refactor: 개인신상관리 상단 td 추가
  inflow/src/views/hr-basic/employee/ProfileView.vue
Labels: enhancement

#159 Feat: 사원정보 등록 입력 양식 가이드 모달 및 인사발령 내역 다운로드 구현
  inflow/src/api/emp_attach.js
  inflow/src/components/common/SelectPeriodComponent.vue
  inflow/src/components/dropdowns/PeriodDropDown.vue
  inflow/src/views/hr-management/EmployeeUploadView.vue
  inflow/src/views/hr-management/appointment/AppointmentHistoryView.vue
  inflow/src/views/hr-management/appointment/AppointmentUploadView.vue
  inflow/src/views/hr-management/employee-upload/CareerInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/DisciplineRewardInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EducationInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/FamilyMemberInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/LanguageTestInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/QualificationInfoUploadView.vue
Labels: enhancement

#158 Client : 리더평가 조회 시 과제 List API 연동
  inflow/src/api/evaluation.js
  inflow/src/views/evaluation/EvalPolicyManagementView.vue
  inflow/src/views/evaluation/EvalTypeManagementView.vue
  inflow/src/views/evaluation/PersonalEvalCreateAndFindView.vue
  inflow/src/views/evaluation/leader/DeptTaskUploadView.vue
  inflow/src/views/evaluation/leader/FeedbackManageView.vue
  inflow/src/views/evaluation/leader/LeaderEvalListView.vue
Labels: enhancement

#162 Feat: 인사기본 사원 부가정보 수정 입력 양식 예제 모달 구현
  inflow/src/api/emp_attach.js
  inflow/src/views/hr-basic/employee/CareerInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/DisciplineRewardInfoView.vue
  inflow/src/views/hr-basic/employee/EducationInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoView.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoView.vue
Labels: enhancement

#163 Refactor: myinfoview 컴포넌트에 props 추가
  inflow/src/router/index.js
  inflow/src/views/hr-basic/MyInfoView.vue
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoView.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoView.vue
Labels: enhancement

#165 Refactor : 자기평가 조회 시 리더평가 리스트 조회 안되도록 수정
  inflow/src/api/evaluation.js
  inflow/src/views/evaluation/PersonalEvalFindView.vue
Labels: enhancement

#164 Feat: myinfocomponent 생성
  inflow/src/components/common/MyInfoComponent.vue
  inflow/src/router/index.js
  inflow/src/views/hr-basic/MyInfoView.vue
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoView.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoView.vue
  inflow/src/views/hr-management/EmployeeInfoView.vue
Labels: enhancement

#168 fix: 서브메뉴 관련 index.js 수정
  inflow/src/router/index.js
Labels: enhancement

#167 Feat: 코드블럭 하이라이팅 표시 구현
  inflow/package-lock.json
  inflow/package.json
  inflow/src/assets/main.css
  inflow/src/components/common/CommonNav.vue
  inflow/src/views/chatbot/ChatbotView.vue
Labels: enhancement

#169 Fix: 인사기본 사원 정보 수정 버튼 노출 조건 변경
  inflow/src/components/employee-search/EmployeeList.vue
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoView.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoView.vue
  inflow/src/views/hr-management/EmployeeInfoView.vue
Labels: enhancement

#171 Feat: 인사관리 사원 조회 페이지 구현
  inflow/src/api/emp_attach.js
  inflow/src/components/common/MyInfoComponent.vue
  inflow/src/views/hr-basic/employee/CareerInfoVIew.vue
  inflow/src/views/hr-basic/employee/DisciplineRewardInfoView.vue
  inflow/src/views/hr-basic/employee/EducationInfoView.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoView.vue
  inflow/src/views/hr-basic/employee/ProfileView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoView.vue
  inflow/src/views/hr-management/EmployeeInfoView.vue
Labels: enhancement

#173 Feat: 평가 관련 오류 수정
  inflow/src/api/evaluation.js
  inflow/src/views/evaluation/EvalPolicyManagementView.vue
  inflow/src/views/evaluation/EvalPolicyUpdateAndViewModal.vue
  inflow/src/views/evaluation/PersonalEvalCreateAndFindView.vue
  inflow/src/views/evaluation/PersonalEvalFindView.vue
  inflow/src/views/evaluation/TaskEvalModal.vue
Labels: enhancement

#174 Fix: 첫 화면에서 급여 명세 조회시 사원id가 전달되지 않는 문제 수정
  inflow/src/views/hr-basic/salary/SalaryDetailView.vue
Labels: bug, enhancement

#176 Refactor: 인사기본 급여및수당 서브메뉴 순서 교체
  inflow/src/router/index.js
  inflow/src/views/hr-basic/SalaryView.vue
Labels: enhancement

#177 양식 다운로드 기능 수정
  inflow/src/components/employee-search/EmployeeList.vue
  inflow/src/views/evaluation/EvalPolicyManagementView.vue
  inflow/src/views/evaluation/PersonalEvalCreateAndFindView.vue
  inflow/src/views/hr-management/appointment/AppointmentUploadView.vue
  inflow/src/views/hr-management/employee-upload/CareerInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/DisciplineRewardInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EducationInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/FamilyMemberInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/LanguageTestInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/QualificationInfoUploadView.vue
Labels: enhancement

#182 홈 화면 추가
  inflow/src/App.vue
  inflow/src/api/axios.js
  inflow/src/api/emp_info.js
  inflow/src/components/common/CommonNav.vue
  inflow/src/router/index.js
  inflow/src/views/chatbot/ChatbotView.vue
  inflow/src/views/emp-search/EmployeeSearchView.vue
  inflow/src/views/evaluation/EvalPolicyView.vue
  inflow/src/views/evaluation/EvalTaskView.vue
  inflow/src/views/evaluation/LeaderEvalView.vue
  inflow/src/views/evaluation/PersonalEvalView.vue
  inflow/src/views/evaluation/TaskPolicyView.vue
  inflow/src/views/home/HomeView.vue
  inflow/src/views/hr-basic/AttendanceView.vue
  inflow/src/views/hr-basic/ContractView.vue
  inflow/src/views/hr-basic/MyDepartmentView.vue
  inflow/src/views/hr-basic/MyInfoView.vue
  inflow/src/views/hr-basic/SalaryView.vue
  inflow/src/views/hr-management/AppointmentManagementView.vue
  inflow/src/views/hr-management/ContractManagementView.vue
  inflow/src/views/hr-management/DepartmentManagementView .vue
  inflow/src/views/hr-management/EmployeeInfoView.vue
  inflow/src/views/hr-management/EmployeeUploadView.vue
  inflow/src/views/hr-management/SalaryManagementView.vue
  inflow/src/views/hr-management/VacationManagementView.vue
  inflow/src/views/login/LoginView.vue
Labels: enhancement

#181 Refactor: input에 대한 id값 추가
  inflow/src/components/employee-search/SearchBar.vue
  inflow/src/views/hr-basic/my-department/SearchDepartmentMember.vue
  inflow/src/views/hr-management/department/DepartmentManagementAddView.vue
  inflow/src/views/hr-management/department/DepartmentManagementInformationView.vue
  inflow/src/views/hr-management/department/DepartmentSearch.vue
Labels: enhancement

#186 Refactor: input 태그에 id 속성 추가
  inflow/package-lock.json
  inflow/package.json
  inflow/src/views/hr-basic/employee/CareerInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/EducationInfoUpdateVIew.vue
  inflow/src/views/hr-basic/employee/FamilyMemberInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/LanguageTestInfoUpdateView.vue
  inflow/src/views/hr-basic/employee/QualificationInfoUpdateView.vue
  inflow/src/views/hr-management/EmployeeInfoView.vue
  inflow/src/views/hr-management/appointment/AppointmentUploadView.vue
  inflow/src/views/hr-management/employee-upload/CareerInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/DisciplineRewardInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EducationInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/FamilyMemberInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/LanguageTestInfoUploadView.vue
  inflow/src/views/hr-management/employee-upload/QualificationInfoUploadView.vue
Labels: enhancement

#190 Build: 환경 변경
  .github/workflows/deploy.yml
Labels: enhancement

#189 Refactor: 부서 css 아이콘 추가
  src/assets/icons/search_icon.svg
  src/components/employee-search/TreeNode.vue
  src/router/index.js
  src/views/hr-basic/my-department/SearchDepartmentMember.vue
  src/views/hr-management/DepartmentManagementView .vue
Labels: enhancement

#191 Refactor : 평가 컴포넌트 수정
  src/api/evaluation.js
  src/views/evaluation/EvalGradeView.vue
  src/views/evaluation/EvalPolicyManagementView.vue
  src/views/evaluation/EvalPolicyUpdateAndViewModal.vue
  src/views/evaluation/PersonalEvalCreateAndFindView.vue
  src/views/evaluation/leader/DeptTaskAssignView.vue
  src/views/evaluation/leader/DeptTaskUploadView.vue
  src/views/evaluation/leader/FeedbackManageView.vue
  src/views/evaluation/leader/LeaderEvalListView.vue
  src/views/evaluation/leader/TaskEvalCreateAndUpdateModal.vue
Labels: enhancement

#192 Refactor : 과제 할당 및 평가, 피드백 서브메뉴에 적용된 사원 검색 컴포넌트 변경
  src/components/common/SearchDepartmentMembersByDepartmentCodeComponent.vue
  src/components/common/SearchEmployeeComponent.vue
  src/views/evaluation/leader/DeptTaskAssignView.vue
  src/views/evaluation/leader/FeedbackManageView.vue
Labels: enhancement

#194 Refactor: 사원 찾기 detail 이미지 크기 조절
  src/components/employee-search/EmployeeDetail.vue
Labels: enhancement

#195 Refactor: 부서 추가/ 부서 정보 조회 오타 수정
  src/views/hr-management/department/DepartmentManagementAddView.vue
  src/views/hr-management/department/DepartmentManagementInformationView.vue
Labels: enhancement

#196 Refactor: https 도입
  src/api/axios.js
Labels: enhancement

#197 Refactor: 로그인 axios 변경
  src/api/axios.js
  src/api/emp_info.js
Labels: enhancement

#199 Refactor: 월급에 쉼표(,) 추가
  src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
Labels: enhancement

#200 챗봇 통신 추가
  inflow/package-lock.json
  src/api/axios.js
  src/api/chatbot.js
  src/views/chatbot/ChatbotView.vue
Labels: enhancement

#201 Refactor : YearDropdown, YearMonthDropdown 수정
  src/api/axios.js
  src/api/emp_info.js
  src/components/common/SearchDepartmentMembersByDepartmentCodeComponent.vue
  src/components/dropdowns/YearDropDown.vue
  src/views/evaluation/EvalGradeView.vue
  src/views/evaluation/EvalPolicyManagementView.vue
  src/views/evaluation/PersonalEvalCreateAndFindView.vue
  src/views/evaluation/PersonalEvalFindView.vue
  src/views/evaluation/leader/DeptTaskAssignView.vue
  src/views/evaluation/leader/DeptTaskUploadView.vue
  src/views/evaluation/leader/FeedbackManageView.vue
  src/views/evaluation/leader/LeaderEvalListView.vue
  src/views/hr-basic/MyDepartmentView.vue
Labels: enhancement

#203 Refactor: 급여 명세 툴팁 아이콘 수정
  src/api/emp_info.js
  src/views/hr-basic/salary/SalaryDetailView.vue
Labels: enhancement

#202 Refactor: api http로 변경
  src/api/axios.js
  src/api/emp_info.js
Labels: enhancement

#205 Refactor: 출퇴근 드롭다운 변경
  src/views/hr-basic/attendance/CommuteView.vue
Labels: enhancement

#207 Fix: 사원 정보 등록 오류 수정
  src/api/emp_info.js
  src/views/hr-management/employee-upload/EducationInfoUploadView.vue
  src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  src/views/hr-management/employee-upload/LanguageTestInfoUploadView.vue
Labels: enhancement

#208 Refactor: 급여 명세 툴팁 텍스트 색 변경
  src/views/hr-basic/salary/SalaryDetailView.vue
Labels: enhancement

#209 Refactor: 디자인 수정
  src/api/axios.js
  src/components/employee-search/DepartmentHeirarchy.vue
  src/components/employee-search/EmployeeList.vue
  src/components/employee-search/TreeNode.vue
  src/components/icons/FolderOpenIcon.vue
  src/views/hr-management/EmployeeInfoView.vue
  src/views/hr-management/vacation/VacationPolicyView.vue
Labels: enhancement

#210 Feat: 포상 및 징계 조회 api 변경
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/api/axios.js
  src/api/emp_attach.js
  src/api/emp_info.js
  src/views/hr-basic/employee/DisciplineRewardInfoView.vue
  src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
Labels: enhancement

#211 Build: 재배포용 풀 리퀘스트
  README.md
  src/components/dropdowns/YearMonthDropDown.vue
  src/views/hr-management/employee-upload/EmployeeInfoUploadView.vue
  src/views/login/LoginView.vue
Labels: enhancement

#212 Fix: 사원 정보 조회 api 중복 호출 해결
  src/views/hr-basic/employee/CareerInfoVIew.vue
  src/views/hr-basic/employee/DisciplineRewardInfoView.vue
  src/views/hr-basic/employee/EducationInfoView.vue
  src/views/hr-basic/employee/FamilyMemberInfoView.vue
  src/views/hr-basic/employee/LanguageTestInfoView.vue
  src/views/hr-basic/employee/QualificationInfoView.vue
Labels: enhancement

#213 챗봇 UI 설정
  src/api/emp_info.js
  src/views/chatbot/ChatbotView.vue
Labels: enhancement

#214 Refactor: 챗봇 ui 수정
  src/api/axios.js
  src/api/emp_info.js
  src/views/chatbot/ChatbotView.vue
  src/views/evaluation/PersonalEvalCreateAndFindView.vue
  src/views/home/HomeView.vue
  src/views/hr-basic/document/EmployeeContractModal.vue
  src/views/hr-basic/document/SecurityContractModal.vue
  src/views/hr-basic/employee/DisciplineRewardInfoView.vue
Labels: enhancement

#215 Refactor : 부서구성원만 조회되도록 컴포넌트 함수 수정
  src/api/department.js
  src/api/emp_info.js
  src/components/common/SearchDepartmentMembersByDepartmentCodeComponent.vue
  src/components/common/SearchEmployeeComponent.vue
  src/views/evaluation/EvalPolicyManagementView.vue
Labels: enhancement

#216 fix : 함수 import 안된것 수정 및 버튼 패딩 조절
  src/api/axios.js
  src/api/emp_info.js
  src/components/common/SearchDepartmentMembersByDepartmentCodeComponent.vue
  src/views/evaluation/leader/DeptTaskAssignView.vue
Labels: enhancement

#217 Fix : axios 및 emp_info 주석 변경
  src/api/axios.js
  src/api/emp_info.js
Labels: bug

#218 Refactor: 아이콘 수정
  src/components/employee-search/TreeNode.vue
  src/views/evaluation/EvalGradeView.vue
  src/views/evaluation/EvalPolicyManagementView.vue
  src/views/evaluation/EvalTypeManagementView.vue
Labels: enhancement

#219 Refactor: 메뉴 이름 변경
  src/views/evaluation/EvalPolicyManagementView.vue
  src/views/evaluation/EvalPolicyUpdateAndViewModal.vue
  src/views/evaluation/EvalPolicyView.vue
  src/views/evaluation/EvalTypeManagementView.vue
  src/views/evaluation/PersonalEvalCreateAndFindView.vue
  src/views/evaluation/PersonalEvalView.vue
  src/views/evaluation/leader/DeptTaskUploadView.vue
Labels: enhancement

#220 Refactor: 현재년도부터 뜨게 수정
  src/views/evaluation/EvalGradeView.vue
Labels: enhancement

#221 Refactor: 챗봇 응답 링크 뜨는 조건 수정
  src/views/chatbot/ChatbotView.vue
Labels: enhancement
